# Generated by Django 3.1.4 on 2021-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=18)),
                ('portrait', models.BooleanField(default=False)),
                ('bw', models.BooleanField(default=False)),
            ],
        ),
    ]
